---
- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install nginx
  apt:
    name: nginx
    state: present

- name: start_enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: copy template site page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
